sonata_admin:
    title: 'Sonata Admin'
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }
    security:
        role_super_admin: ROLE_ADMIN
        role_admin: ROLE_MODERATOR

sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
