twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    exception_controller: App\Controller\ErrorController::index
    form_themes: ['bootstrap_4_horizontal_layout.html.twig']
