#index:
#    path: /
#    controller: App\Controller\DefaultController::index
#first_page:
#  path: /welcome
#  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
#  defaults:
#    template: 'first_page.html.twig'
#welcome:
#  path: /welcome
#  conttroller:
homepage:
  path: /
  controller: App\Controller\PostController::index