#index:
#    path: /
#    controller: App\Controller\DefaultController::index
first_page:
  path: /aaa
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
  defaults:
    template: 'first_page.html.twig'